### PR TITLE
Updated tech level for spacer start to use Spacer definition

### PR DESCRIPTION
**Pull request by brandon-thimmesch**
Love the mod but realized the tech level was still set to Industrial. I don't know if this was intended or not, but I tested locally and this def works for allowing full research speed on all tiers.

### CODE REVIEW

**Comment by mariusfranzen** [comment]
Thank you for the kind words. I'm thinking of implementing a mod settings menu, and I will add the option to change tech levels to that menu along with some other things. For now I think I will keep it set to industrial however, since it's such a massive change to the research speed.

**Comment by brandon-thimmesch** [comment]
Sounds great, thank you for responding. I'm looking forward to having that menu available. I will go ahead and close this pull request then. Good luck with your development!

**Comment by mariusfranzen** [comment]
Thank you! And I appreciate the feedback, so if there's anything else, feel free to tell me :)

**Comment by mariusfranzen** [comment]
It's now been implemented

**Comment by brandon-thimmesch** [comment]
Oh awesome, thanks for adding that! I'm looking forward to seeing what else you end up doing with this mod. =)

**Pull request closed without merging**
